[build]
builder = "nixpacks"
buildCommand = "npm install"

[install]
installCommand = "npm install"

[deploy]
startCommand = "node app.js --mode prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"